[sOutline]
X=0
Y=0
UpdateDivider=10000

[sGradient]
X=5
Y=4
ImageName=#SKINSPATH#Rainify\@Settings\Gradient.png
UpdateDivider=10000

[sTextArea]
X=5
Y=4
W=200
SolidColor=#color.Skin#

[sButton]
X=16r
Y=12
MouseActionCursor=1
Hidden=1

[sX]
X=196
Y=7
FontColor=#color.Title#
FontFace=Webdings
FontSize=5
StringEffect=SHADOW
FontEffectColor=00000020
Text=r
LeftMouseUpAction=!RainmeterDeactivateConfig
RightMouseUpAction=!RainmeterActivateConfig "Rainify\@Settings" "Settings.ini"
MouseActionCursor=1
AntiAlias=1
Hidden=1

[sTitle]
X=320
Y=56
W=190
H=19
FontColor=#color.Title#
FontFace=#font.Name#
FontSize=9
StringCase=NONE
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=00000040
StringAlign=LEFT
ClipString=1
AntiAlias=1

[sLeft]
X=r
Y=8r
H=14
W=160
ClipString=1
FontColor=#color.Text#
FontFace=#font.Name#
FontSize=#text.Size#
StringCase=NONE
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=00000020
StringAlign=LEFT
AntiAlias=1

[sRight]
X=200
Y=0r
H=14
W=190
ClipString=1
FontColor=#color.Text#
FontFace=#font.Name#
FontSize=#text.Size#
StringCase=NONE
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=00000020
StringAlign=RIGHT
AntiAlias=1

[sBar]
X=5
Y=28r
W=200
H=1
BarColor=#color.Highlight#
SolidColor=00000000
BarOrientation=HORIZONTAL