; ----------------------
; I HIGHLY RECCOMENDED USING THE CONFIGURATION TOOL (ConfigTool.exe) TO CHANGE SETTINGS
; ConfigTool.exe is located in the same folder as this file
; ----------------------

[Variables]
font.Name=Aller
text.Size=7
color.Skin=00000099
color.Title=255,255,255,255
color.Text=255,255,255,255
color.Highlight=669933FF
disks.1=C:
disks.2=D:
disks.3=E:
disks.4=F:
disks.5=1054206
disks.6=992056
disks.7=861070
disks.8=1187656
weather.Code=UKXX0085
weather.Unit=C
mail.User=Bonsitm
mail.Pass=drowssap1
feeds.URL1=http%3A%2F%2Fnews.google.com%2Fnews%3Fpz%3D1%26cf%3Dall%26ned%3Dus%26hl%3Den%26topic%3Dh%26num%3D3%26output%3Drss
feeds.URL2=http%3A%2F%2Ffeeds.gawker.com%2Fgizmodo%2Fexcerpts.xml
feeds.URL3=http%3A%2F%2Fwww.xkcd.com%2Fatom.xml
feeds.URL4=http%3A%2F%2Ffeeds.gawker.com%2Flifehacker%2Fexcerpts.xml
substitute.Item=#Normal#
network.MaxUp=10485760
network.MaxDown=12582912
slideshow.Path=Sample
